[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solcVersion = "0.8.25"
evmVersion = "cancun"
optimizer = true
optimizerRuns = 200
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/contracts/"]
